void bad_case::run()
bad_case::ExceptionBase::ExceptionBase()
addr: 0x16b236de8
bad_case::ExceptionDerived::ExceptionDerived()
addr: 0x16b236de8
void bad_case::foo(ExceptionBase &)
bad_case::ExceptionBase::ExceptionBase(const ExceptionBase &)
addr: 0x145704130
there is an exception, add: 0x145704130

void solution::run()
solution::ExceptionBase::ExceptionBase()
addr: 0x16b236de8
solution::ExceptionDerived::ExceptionDerived()
addr: 0x16b236de8
void solution::foo(ExceptionBase &)
solution::ExceptionBase::ExceptionBase(const ExceptionBase &)
addr: 0x145704110
solution::ExceptionDerived::ExceptionDerived(const ExceptionDerived &)
addr: 0x145704110
ExceptionDerived, addr: 0x145704110

void rethrow::catch_rethrow(void (*)())
void rethrow::run_rethrow_1()
solution::ExceptionBase::ExceptionBase()
addr: 0x16b236d48
solution::ExceptionDerived::ExceptionDerived()
addr: 0x16b236d48
void solution::foo(ExceptionBase &)
solution::ExceptionBase::ExceptionBase(const ExceptionBase &)
addr: 0x145704110
solution::ExceptionDerived::ExceptionDerived(const ExceptionDerived &)
addr: 0x145704110
ExceptionBase, rethrow, addr: 0x145704110
solution::ExceptionBase::ExceptionBase(const ExceptionBase &)
addr: 0x1457041d0
there is an exception, addr: 0x1457041d0

void rethrow::catch_rethrow(void (*)())
void rethrow::run_rethrow_2()
solution::ExceptionBase::ExceptionBase()
addr: 0x16b236d48
solution::ExceptionDerived::ExceptionDerived()
addr: 0x16b236d48
void solution::foo(ExceptionBase &)
solution::ExceptionBase::ExceptionBase(const ExceptionBase &)
addr: 0x145704110
solution::ExceptionDerived::ExceptionDerived(const ExceptionDerived &)
addr: 0x145704110
ExceptionBase, rethrow, addr: 0x145704110
ExceptionBase, rethrow, addr: 0x145704110

void rethrow::catch_rethrow(void (*)())
void rethrow::run_rethrow_3()
solution::ExceptionBase::ExceptionBase()
addr: 0x16b236d48
solution::ExceptionDerived::ExceptionDerived()
addr: 0x16b236d48
void solution::foo(ExceptionBase &)
solution::ExceptionBase::ExceptionBase(const ExceptionBase &)
addr: 0x145704110
solution::ExceptionDerived::ExceptionDerived(const ExceptionDerived &)
addr: 0x145704110
ExceptionBase, rethrow, addr: 0x145704110
solution::ExceptionBase::ExceptionBase(const ExceptionBase &)
addr: 0x1457041a0
solution::ExceptionDerived::ExceptionDerived(const ExceptionDerived &)
addr: 0x1457041a0
ExceptionBase, rethrow, addr: 0x1457041a0
